# Generated by Django 4.2.1 on 2023-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_PREPARING', 'Order is being prepared'), ('ORDER_READY', 'Order is ready for you'), ('ORDER_DISPATCHED', 'Order dispatched')], default='ORDER_PREPARING', max_length=20),
        ),
    ]
