# Generated by Django 4.2.1 on 2023-07-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_alter_useractivity_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_name',
        ),
    ]
